-- MySQL Script generated by MySQL Workbench
-- Du 14 ian 2024 19:26:26 +0200
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE SCHEMA IF NOT EXISTS `PawDB` DEFAULT CHARACTER SET utf8mb4 ;
USE `PawDB` ;


CREATE TABLE IF NOT EXISTS `PawDB`.`Utilizator` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nume` TINYTEXT NOT NULL,
  `parola` BLOB NOT NULL,
  PRIMARY KEY (`id`));


CREATE TABLE IF NOT EXISTS `PawDB`.`MaterialCurs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `denumire` TINYTEXT NOT NULL,
  `date` BLOB NOT NULL,
  `dataIntroducerii` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
DEFAULT CHARACTER SET = utf8mb4;